# Generated by Django 4.1.7 on 2023-04-11 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_payhistory_paid_payhistory_paystack_access_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_price_id', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='membership',
            name='price',
        ),
        migrations.AddField(
            model_name='membership',
            name='stripe_product_id',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='membership',
            name='slug',
            field=models.SlugField(default=None),
        ),
        migrations.DeleteModel(
            name='PayHistory',
        ),
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.membership'),
        ),
    ]
