# Generated by Django 4.1.7 on 2023-04-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_price_remove_membership_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontaktai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(max_length=20)),
                ('elpastas', models.EmailField(max_length=30)),
                ('komentaras', models.TextField(max_length=400)),
            ],
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='reference_code',
        ),
    ]
