# Generated by Django 4.1.7 on 2023-04-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_kontaktai_remove_usermembership_reference_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='customer_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
